--CATEGORY--
CREATE TABLE CATEGORY
(
    CAT_ID      NUMBER (7),
    CAT_NAME    VARCHAR2 (50 BYTE),
    CAT_TYPE    VARCHAR2 (50 BYTE),
    QUANTITY    NUMBER (7),
    MIN_RATE    VARCHAR2 (25 BYTE),
    MAX_RATE    VARCHAR2 (25 BYTE),
    USER_ID     NUMBER (7)
);
--company--
CREATE TABLE COMPANY
(
    RESTAURANT_ID      NUMBER (7),
    RESTAURANT_NAME    VARCHAR2 (50 BYTE),
    LOCATION           VARCHAR2 (50 BYTE),
    CITY               VARCHAR2 (50 BYTE),
    COUNTRY            VARCHAR2 (50 BYTE),
    ZIP_CODE           NUMBER (7)
);
--CUSTOMER--
CREATE TABLE CUSTOMER
(
    CUSTOMER_ID      NUMBER (7),
    NAME             VARCHAR2 (50 BYTE),
    PHN_NO           VARCHAR2 (25 BYTE),
    EMAIL            VARCHAR2 (50 BYTE),
    CREDIT_LIMITS    NUMBER (5),
    URL              VARCHAR2 (100 BYTE),
    TAG              VARCHAR2 (1000 BYTE),
    USER_ID          NUMBER (7)
);
--EMPLOYEES--
CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID          NUMBER (7),
    FIRST_NAME           VARCHAR2 (25 BYTE),
    LAST_NAME            VARCHAR2 (25 BYTE),
    ADDRESS              VARCHAR2 (25 BYTE),
    PHONE_NO             VARCHAR2 (20 BYTE),
    EMAIL                VARCHAR2 (50 BYTE),
    NID                  VARCHAR2 (50 BYTE),
    HIRE_DATE            DATE,
    IMAGE                BLOB,
    MIMETYPE             VARCHAR2 (50),
    IMAGE_LAST_UPDATE    TIMESTAMP WITH LOCAL TIME ZONE,
    FILENAME             VARCHAR2 (100),
    JOB_TITLE            VARCHAR2 (30 BYTE),
    department_Name      VARCHAR2 (30 BYTE),
    SALARY               NUMBER (7),
    RESTAURANT_ID        NUMBER (7)
);
--MENU--
CREATE TABLE MENU
(
    MENU_ID         NUMBER (7),
    MENU_NAME       VARCHAR2 (200 BYTE),
    TYPE_OR_SIZE    VARCHAR2 (25 BYTE),
    PRICE           NUMBER (6),
    CAT_ID          NUMBER (7)
);
--ORDER_DETAIL--
CREATE TABLE ORDER_DETAIL
(
    ORDER_DETAIL_ID     NUMBER (7),
    DISCOUNT            NUMBER (7),
    VAT                 NUMBER (7),
    TOTAL_AMOUNT        NUMBER (7),
    ORDER_MST_ID        NUMBER (7),
    PRODUCT_ID          NUMBER (7),
    PAYABLE_AMOUNT      NUMBER (7),
    PAID                NUMBER(7),
    CHANGE              NUMBER(7),
    PAYMODE             VARCHAR2 (50 BYTE),
    PRODUCT_NAME        VARCHAR2 (300 BYTE),
    PRODUCT_CATEGORY    VARCHAR2 (300 BYTE),
    UOM                 VARCHAR2 (250 BYTE),
    SALES_PRICE         VARCHAR2 (250 BYTE),
    PRODUCT_QUANTITY    VARCHAR2 (250 BYTE)
);
--ORDER_MASTER--
CREATE TABLE ORDER_MASTER
(
    ORDER_MST_ID       NUMBER (7),
    ORDER_DATE_TIME    DATE,
    CUSTOMER_ID        NUMBER (7),
    USER_ID            NUMBER (7),
    USer_name          VARCHAR2 (100 BYTE),
    EMPLOYEE_ID        NUMBER (7),
    CUSTOMER_NAME      VARCHAR2 (250 BYTE),
    PHONE_NUMBER       VARCHAR2 (20 BYTE),
    TABLE_NO           NUMBER (7)
);
--PRODUCT--
CREATE TABLE PRODUCT
(
    PRODUCT_ID             NUMBER (7),
    PRODUCT_NAME           VARCHAR2 (50 BYTE),
    UOM                    VARCHAR2 (20 BYTE),
    CAT_ID                 NUMBER (7),
    USER_ID                NUMBER,
    LAST_PURCHASE_PRICE    NUMBER,
    SALES_PRICE            NUMBER (7),
    CATEGORY               VARCHAR2 (250 BYTE),
    PRODUCT_IMAGE          BLOB,
    MIMETYPE               VARCHAR2 (50),
    IMAGE_LAST_UPDATE      TIMESTAMP WITH LOCAL TIME ZONE,
    FILENAME               VARCHAR2 (100)
);
--PURCHASE_DETAIL--
CREATE TABLE PURCHASE_DETAIL
(
    PURCHASE_DETAIL_ID     NUMBER (7),
    PRODUCT_QUANTITY       NUMBER (7),
    PAYMENT_AMOUNT         NUMBER (7),
    PRODUCT_ID             NUMBER (7),
    PURCHASE_MST_ID        NUMBER (7),
    LAST_PURCHASE_PRICE    NUMBER (7),
    PRODUCT_NAME           VARCHAR2 (100 BYTE),
    UOM                    VARCHAR2 (50 BYTE),
    VAT                    NUMBER (9),
    DISCOUNT               NUMBER (9),
    TOTAL_AMOUNT           NUMBER (9),
    CATEGORY               VARCHAR2 (250 BYTE),
    EXPIRED_DATE           DATE
);
--PURCHASE_MASTER--
CREATE TABLE PURCHASE_MASTER
(
    PURCHASE_MST_ID      NUMBER (7),
    PURCHASE_DATE        DATE,
    USER_ID              NUMBER (7),
    SUPPLIERS_ID         NUMBER (7),
    PURCHASE_BY          VARCHAR2 (250 BYTE),
    BILL_NUMBER          VARCHAR2 (250 BYTE),
    SUPPLIERS_NAME       VARCHAR2 (100 BYTE),
    SUPPLIERS_ADDRESS    VARCHAR2 (250 BYTE)
);
--STOCK--
CREATE TABLE STOCK
(
    STOCK_ID           NUMBER (7),
    PRODUCT_ID         NUMBER (7),
    PRODUCT_NAME       VARCHAR2 (25 BYTE),
    STOCK_QTY          NUMBER (6),
    SALES_QTY          NUMBER (6),
    available_stock    VARCHAR2 (25 BYTE)
);
--SUPPLIER--
CREATE TABLE SUPPLIER
(
    SUPPLIERS_ID         NUMBER (7),
    SUPPLIERS_NAME       VARCHAR2 (50 BYTE),
    SUPPLIERS_ADDRESS    VARCHAR2 (50 BYTE),
    CONTACT_PERSON       VARCHAR2 (50 BYTE),
    JOB_TITLE            VARCHAR2 (25 BYTE),
    CONTACT_NO           VARCHAR2 (25 BYTE),
    EMAIL                VARCHAR2 (50 BYTE),
    WEB_ADDRESS          VARCHAR2 (50 BYTE),
    TAG                  VARCHAR2 (2050 BYTE)
);
--TABLE_LIST--
CREATE TABLE TABLE_LIST
(
    ID        NUMBER,
    NAME      VARCHAR2 (25 BYTE),
    STATUS    NUMBER (10)
);
--USERS--
CREATE TABLE USERS
(
    USER_ID          NUMBER (7),
    RESTAURANT_ID    NUMBER (7),
    FIRST_NAME       VARCHAR2 (50 BYTE),
    CONTACT_NO       NUMBER (15),
    ACCOUNT_TYPE     VARCHAR2 (50 BYTE),
    USER_NAME        VARCHAR2 (50 BYTE),
    PASSWORD         VARCHAR2 (25 BYTE)
);
--Primary key --
--CATEGORY --
ALTER TABLE CATEGORY ADD 
  CONSTRAINT MY_CAT_ID_PK
  PRIMARY KEY
  (CAT_ID);
--COMPANY--
ALTER TABLE COMPANY
    ADD (CONSTRAINT RESTAURANT_ID_PK PRIMARY KEY (RESTAURANT_ID));
--CUSTOMER--
ALTER TABLE CUSTOMER
    ADD (CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY (CUSTOMER_ID));
--EMPLOYEES --
ALTER TABLE EMPLOYEES
    ADD (PRIMARY KEY (EMPLOYEE_ID));
--MENU--
ALTER TABLE MENU
    ADD (PRIMARY KEY (MENU_ID));
--ORDER_DETAIL--
ALTER TABLE ORDER_DETAIL
    ADD (CONSTRAINT MY_ORDER_DETAIL_ID_PK PRIMARY KEY (ORDER_DETAIL_ID));
--ORDER_MASTER--
ALTER TABLE ORDER_MASTER
    ADD (CONSTRAINT MY_ORDER_MST_ID_PK PRIMARY KEY (ORDER_MST_ID));
--PRODUCT--
ALTER TABLE PRODUCT
    ADD (CONSTRAINT MY_PRODUCT_ID_PK PRIMARY KEY (PRODUCT_ID));
--PURCHASE_DETAIL--
ALTER TABLE PURCHASE_DETAIL
    ADD (CONSTRAINT MY_PURCHASE_DETAIL_PK PRIMARY KEY (PURCHASE_DETAIL_ID));
--PURCHASE_MASTER--
ALTER TABLE PURCHASE_MASTER
    ADD (CONSTRAINT MY_PURCHASE_MST_PK PRIMARY KEY (PURCHASE_MST_ID));
--SUPPLIER--
ALTER TABLE SUPPLIER
    ADD (CONSTRAINT SUPPLIERS_ID_PK PRIMARY KEY (SUPPLIERS_ID));
--USERS--
ALTER TABLE USERS
    ADD (CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID));
--FOREIGN KEY--
ALTER TABLE CATEGORY
    ADD (FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID));
--EMPLOYEES--
ALTER TABLE EMPLOYEES
    ADD (FOREIGN KEY (RESTAURANT_ID) REFERENCES COMPANY (RESTAURANT_ID)) ;
--MENU--
ALTER TABLE MENU
    ADD (FOREIGN KEY (CAT_ID) REFERENCES CATEGORY (CAT_ID));
--ORDER_DETAIL--
ALTER TABLE ORDER_DETAIL
    ADD (
        CONSTRAINT MY_ORDER_MST_ID_FK FOREIGN KEY (ORDER_MST_ID)
            REFERENCES ORDER_MASTER (ORDER_MST_ID));
--ORDER_MASTER--
ALTER TABLE ORDER_MASTER
    ADD (
        CONSTRAINT MY_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID)
            REFERENCES CUSTOMER (CUSTOMER_ID));
ALTER TABLE ORDER_MASTER
    ADD (FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID));
--PRODUCT--
ALTER TABLE PRODUCT
    ADD (
        CONSTRAINT PRODUCT_DT_FK FOREIGN KEY (CAT_ID)
            REFERENCES CATEGORY (CAT_ID));
--PURCHASE_DETAIL--
ALTER TABLE PURCHASE_DETAIL
    ADD (
        CONSTRAINT MY_PRODUCTID_FK FOREIGN KEY (PRODUCT_ID)
            REFERENCES PRODUCT (PRODUCT_ID));
ALTER TABLE PURCHASE_DETAIL
    ADD (
        CONSTRAINT MY_PURCHASE_MST_FK FOREIGN KEY (PURCHASE_MST_ID)
            REFERENCES PURCHASE_MASTER);
--PURCHASE_MASTER--
ALTER TABLE PURCHASE_MASTER
    ADD (FOREIGN KEY (SUPPLIERS_ID) REFERENCES SUPPLIER (SUPPLIERS_ID));
ALTER TABLE PURCHASE_MASTER
    ADD (FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID));
--USERS --
ALTER TABLE USERS
    ADD (
        CONSTRAINT RESTAURANT_ID_FK FOREIGN KEY (RESTAURANT_ID)
            REFERENCES COMPANY (RESTAURANT_ID));




















